server:
  port: 8080

logging:
  level:
    root: INFO
  
spring:
    config:
        import: optional:file:dev.env[.properties]
    output:
        ansi:
            enabled: always
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update

        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver